import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.css";
import StoreProvider from "@/app/components/StoreProvider";
import ScrollToTopButton from "@/app/components/Scrolltotop";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Promixity Service",
  description: "Generated by QKIT intern team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/03244eb91d.js"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className={popins.className}>
        <ScrollToTopButton />
        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
