export enum ERRORS_DICTIONARY {
  // AUTH
  AUTH_EMAIL_EXISTED = 'ATH_0091',
  AUTH_EMAIL_NOT_EXISTED = 'ATH_0041',
  AUTH_WRONG_CREDENTIALS = 'ATH_0001',
  AUTH_CONTENT_NOT_MATCH = 'ATH_0002',
  AUTH_UNAUTHORIZED_EXCEPTION = 'ATH_0011',
  AUTH_TOKEN_EXPIRED = 'ATH_0012',
  AUTH_INVALID_TOKEN = 'ATH_0013',
  AUTH_PASSWORD_NOT_MATCH = 'ATH_0031',
  AUTH_TOKEN_RESET_EXEEDED_LIMIT = 'ATH_0291',
  AUTH_OTP_NOT_MATCH = 'OTP_0001',

  //OTP
  OTP_EXCEEDED_LIMIT = 'OTP_0291',
  OTP_EMAIL_EXISTED = 'OTP_0091',

  // USER
  USER_NOT_FOUND = 'USR_0041',
  USER_ALREADY_EXIST = 'USR_0091',
  USER_DISABLED = 'USR_0043',
  USER_NEW_PASSWORD_NOT_MATCH_OLD = 'USR_0031',
  USER_CONFIRM_PASSWORD_NOT_MATCH = 'USR_0032',
  // BUSINESS
  BUSINESS_NOT_FOUND = 'BUS_0041',
  BUSINESS_ALREADY_EXIST = 'BUS_0042',
  BUSINESS_DISABLED = 'BUS_0043',

  // CLASS VALIDATOR
  VALIDATION_ERROR = 'CVL_0001',
  INVALID_INPUT = 'CVL_0002',
}

export const ERROR_MESSAGES = {
  [ERRORS_DICTIONARY.AUTH_EMAIL_EXISTED]: 'Email already exists.',
  [ERRORS_DICTIONARY.AUTH_EMAIL_NOT_EXISTED]: 'Email not exists.',
  [ERRORS_DICTIONARY.AUTH_WRONG_CREDENTIALS]: 'Incorrect username or password.',
  [ERRORS_DICTIONARY.AUTH_CONTENT_NOT_MATCH]: 'Content does not match.',
  [ERRORS_DICTIONARY.AUTH_UNAUTHORIZED_EXCEPTION]: 'Unauthorized access.',

  [ERRORS_DICTIONARY.AUTH_TOKEN_EXPIRED]: 'Token has expired.',
  [ERRORS_DICTIONARY.AUTH_INVALID_TOKEN]: 'Invalid token.',
  [ERRORS_DICTIONARY.AUTH_PASSWORD_NOT_MATCH]: 'Password does not match.',
  [ERRORS_DICTIONARY.AUTH_TOKEN_RESET_EXEEDED_LIMIT]:
    'Token for reset password exceeded limit.',

  //OTP
  [ERRORS_DICTIONARY.OTP_EXCEEDED_LIMIT]: 'OTP exceeded limit.',

  [ERRORS_DICTIONARY.USER_NOT_FOUND]: 'User not found.',
  [ERRORS_DICTIONARY.USER_ALREADY_EXIST]: 'User already exists.',
  [ERRORS_DICTIONARY.USER_DISABLED]: 'User is disabled.',
  [ERRORS_DICTIONARY.USER_NEW_PASSWORD_NOT_MATCH_OLD]:
    'New password does not match with old password.',
  [ERRORS_DICTIONARY.USER_CONFIRM_PASSWORD_NOT_MATCH]:
    'Confirm password does not match.',

  [ERRORS_DICTIONARY.BUSINESS_NOT_FOUND]: 'Business not found.',
  [ERRORS_DICTIONARY.BUSINESS_ALREADY_EXIST]: 'Business already exists.',
  [ERRORS_DICTIONARY.BUSINESS_DISABLED]: 'Business is disabled.',
};

// Path: packages/backend/src/common/constants/upload.constant.ts
