export enum ConfigKey {
  JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
  JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',
  SECRET_KEY = 'SECRET_KEY',
  REFRESH_TOKEN_KEY = 'REFRESH_TOKEN_KEY',
  CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME',
  CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET',
  CLOUDINARY_IMAGE_FOLDER = 'CLOUDINARY_IMAGE_FOLDER',
  MONGO_HOST = 'MONGO_HOST',
  MONGO_PORT = 'MONGO_PORT',
  MONGO_NAME = 'Blog_App',
  PROJECT_ENVIRONMENT = 'NODE_ENV',
}
