version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: nest-docker-postgres
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    ports:
      - '27019:27017'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
volumes:
  mongodb_data:
